name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: ianwalter/puppeteer-container@v4.0.0
        with:
          args: pnpm i

      # Check for regressions
      - run: yarn run lint

      # Run tests
      - run: yarn run test:ci
